import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";

/**
 * These tests validate the sitemap.xml and robots.txt generated by the build.
 * Precondition: run `CONTENT_DIR=test/content bun run build` before running these tests.
 */
const DIST = path.resolve(process.cwd(), "dist/client");
const SITEMAP_PATH = path.join(DIST, "sitemap.xml");
const ROBOTS_PATH = path.join(DIST, "robots.txt");

const hasBuild = fs.existsSync(SITEMAP_PATH);

describe.skipIf(!hasBuild)("sitemap.xml generation", () => {
  it("generates sitemap.xml in dist/client/", () => {
    expect(fs.existsSync(SITEMAP_PATH)).toBe(true);
  });

  it("is valid XML with urlset root element", () => {
    const xml = fs.readFileSync(SITEMAP_PATH, "utf-8");
    expect(xml).toContain('<?xml version="1.0" encoding="UTF-8"?>');
    expect(xml).toContain("<urlset");
    expect(xml).toContain("</urlset>");
  });

  it("includes the home page", () => {
    const xml = fs.readFileSync(SITEMAP_PATH, "utf-8");
    expect(xml).toContain("<loc>http://localhost:4173/</loc>");
  });

  it("includes published post URLs", () => {
    const xml = fs.readFileSync(SITEMAP_PATH, "utf-8");
    expect(xml).toContain("/posts/bun-for-backend</loc>");
    expect(xml).toContain("/posts/spec-driven-development</loc>");
    expect(xml).toContain("/posts/agentic-systems-at-scale</loc>");
  });

  it("excludes draft posts", () => {
    const xml = fs.readFileSync(SITEMAP_PATH, "utf-8");
    expect(xml).not.toContain("/posts/draft-post</loc>");
    expect(xml).not.toContain("/posts/external-talk-demo</loc>");
  });

  it("includes tag pages", () => {
    const xml = fs.readFileSync(SITEMAP_PATH, "utf-8");
    expect(xml).toContain("/tags/typescript</loc>");
    expect(xml).toContain("/tags/bun</loc>");
  });

  it("has lastmod for posts", () => {
    const xml = fs.readFileSync(SITEMAP_PATH, "utf-8");
    const lastmodCount = (xml.match(/<lastmod>/g) ?? []).length;
    expect(lastmodCount).toBeGreaterThan(0);
  });

  it("has changefreq daily for home, weekly for posts", () => {
    const xml = fs.readFileSync(SITEMAP_PATH, "utf-8");
    const firstUrl = xml.split("</url>")[0];
    expect(firstUrl).toContain("<changefreq>daily</changefreq>");
    expect(xml).toContain("<changefreq>weekly</changefreq>");
  });
});

describe.skipIf(!hasBuild)("robots.txt generation", () => {
  it("generates robots.txt in dist/client/", () => {
    expect(fs.existsSync(ROBOTS_PATH)).toBe(true);
  });

  it("contains User-agent and Allow directives", () => {
    const txt = fs.readFileSync(ROBOTS_PATH, "utf-8");
    expect(txt).toContain("User-agent: *");
    expect(txt).toContain("Allow: /");
  });

  it("references the sitemap URL", () => {
    const txt = fs.readFileSync(ROBOTS_PATH, "utf-8");
    expect(txt).toContain("Sitemap: http://localhost:4173/sitemap.xml");
  });
});
